/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: "var(--surface)",
        "surface-container-low": "var(--surface-container-low)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "surface-container-high": "var(--surface-container-high)",
        foreground: "var(--foreground)",
        "on-surface-variant": "var(--on-surface-variant)",
        primary: "var(--primary)",
        "primary-foreground": "var(--primary-foreground)",
        primaryContainer: "var(--primary-container)",
        secondary: "var(--secondary)",
        "secondary-foreground": "var(--secondary-foreground)",
        secondaryContainer: "var(--secondary-container)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        input: "var(--input)",
        ring: "var(--ring)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        popover: "var(--popover)",
        "popover-foreground": "var(--popover-foreground)",
        accent: "var(--accent)",
        "accent-foreground": "var(--accent-foreground)",
        destructive: "var(--destructive)",
        "destructive-foreground": "var(--destructive-foreground)",
        error: "var(--error)",
        "error-container": "var(--error-container)",
        onError: "var(--on-error)",
        onErrorContainer: "var(--on-error-container)",
        tertiary: "var(--tertiary)",
        "tertiary-container": "var(--tertiary-container)",
        onTertiary: "var(--on-tertiary)",
        onTertiaryContainer: "var(--on-tertiary-container)",
      },
      fontFamily: {
        display: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
      boxShadow: {
        ambient: "0 20px 40px rgba(11, 28, 48, 0.06)",
      },
      borderRadius: {
        md: "0.375rem",
        lg: "0.625rem",
        xl: "0.75rem",
      },
    },
  },
  plugins: [],
};